### ISSUE TITLE
Windows: Commands do not complete/return

### ISSUE THREAD

**Issue by mattmazzola** [kiwiupover/ember-cli-surge#83]
I've tried PowerShell a regular Command Prompt and they both have same issue.

When I run any surge command through ember cli such as:
```
ember surge whoami
```
It will execute the command and print out results but never complete or return.  It prevents being able to continue using the prompt.  Even Ctrl-C doesn't force it to quit.

However, if I execute the same command from outside ember, using surge cli directly the commands do return.
```
surge whoami
```
works as expected.

Maybe the ember cli is just passing the arguments through to the actual surge cli and checking for some OS specific return code?

I think first step would be trying to find another windows user and see if they can reproduce.
If they can then find out if it's worth fixing or not.

**Comment by mattmazzola** [comment]
I'm not sure how to debug, but maybe there is a simple test to see if the `process.on('close', ` is even firing
https://github.com/kiwiupover/ember-cli-surge/blob/master/lib/commands/surge.js#L48

**Comment by Robdel12** [comment]
I'm having the same issue, except this is on CI. The deploy is successful but the process never exits, which hangs & eventually fails the build

**Comment by kiwiupover** [comment]
@Robdel12 are you on deploying on a windows machine?

**Comment by Robdel12** [comment]
I'm not. Here's a circle build that's hanging right now: https://circleci.com/gh/thefrontside/emberx-select/81

**Comment by kiwiupover** [comment]
@Robdel12 so glad you are using surge for your docs I think it is a great choice. 

I deploy ember-cli-spinjs with ember surge here https://travis-ci.org/kiwiupover/ember-cli-spinjs/jobs/337606986#L1727 

I will need to have a look into this some more. 

Is circleci free for open source projects?

**Comment by Robdel12** [comment]
It is :) I'd be happy to help too! But I'm not quite sure where to begin debugging

**Comment by kiwiupover** [comment]
thanks for the help. 

check if we are getting in here https://github.com/kiwiupover/ember-cli-surge/blob/master/lib/commands/surge.js#L48

**Comment by Robdel12** [comment]
Hm, curious what's going on. When I SSH into the build and run the deploy it exits fine. 🤔 so why does it not exit from a CI step?

**Comment by kiwiupover** [comment]
I wonder if it is a circleci thing

**Comment by kiwiupover** [comment]
@Robdel12 this is interesting. 
https://surge.sh/help/integrating-with-circleci

**Comment by dpatz** [comment]
Also having the same issue with GitLab CI

**Comment by dpatz** [comment]
Maybe it needs this: https://nodejs.org/api/process.html#process_process_exit_code

**Comment by xtagon** [comment]
I'm also having this issue on CircleCI (Linux, not Windows). The deploy command succeeds but the CI build times out anyway becuase it says it's been too long without output from the command.

**Comment by Robdel12** [comment]
What version are you using? @kiwiupover helped me fix the issue I was having on emberx-select

**Comment by xtagon** [comment]
@Robdel12 ember-cli-surge 1.2.1, ember-cli 2.18.2

**Comment by xtagon** [comment]
Also surge is at 0.20.1

**Comment by kiwiupover** [comment]
@xtagon I just deployed a new version that should fix your issue 

Closed by #136

**Comment by xtagon** [comment]
@kiwiupover Is this in 1.3.0? I am still experiencing the problem with ember-cli 2.18.2, ember-cli-surge 1.3.0, and surge 0.20.1. Any ideas?
